### ISSUE TITLE
Asset Loading does'nt seems to work on Web

### ISSUE THREAD

**Issue by juulieen** [Ephenodrom/Flutter-Global-Config#9]
## Config that I want to load : 
```
{
    "key1": "value1",
    "key2": "value2"
}
```
## "Code" i wrote
```
import 'package:flutter/material.dart';

import 'package:global_configuration/global_configuration.dart';

void main() async {
  GlobalConfiguration().loadFromAsset('app_settings.json');
  print(GlobalConfiguration().appConfig.toString());

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: Text('Flutter Demo Home Page'),
    );
  }
}
```

## Config I did : 
- assets
```
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
```
- of course the package itself
```
dependencies:
  flutter:
    sdk: flutter
  global_configuration: ^1.4.0
```

## I don't have any Error at Runtime :
```
Launching lib/main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:43769/2IaTBAq6l2k=
{}
```

## the things I tried
- try with an invalid path (I got an error saying that it can't find the path (obviously))
- restart the app (nothing change)
- clean cache (to update assets)
